### ISSUE TITLE
Support pdcurses.dll library name for Windows

### ISSUE THREAD

**Issue by tarballs-are-good** [HiTECNOLOGYs/cl-charms#15]
Right now, it's required to rename `pdcurses.dll` to `libcurses.dll`, which we can simply address. A commit soon will address this, but it needs to be tested.

**Comment by tarballs-are-good** [comment]
@tuturto, since you tested on Windows before, do you think you could test again without `libcurses.dll` but rather `pdcurses.dll`?

**Comment by tuturto** [comment]
Sure thing. I'll test that tonight when I'm back at home.

**Comment by tuturto** [comment]
I tested this and it worked without any problems.

**Comment by tarballs-are-good** [comment]
@tuturto, Thanks!
