### ISSUE TITLE
Use something more general than  #+sb-unicode

### ISSUE THREAD

**Issue by tarballs-are-good** [HiTECNOLOGYs/cl-charms#33]
We should allow unicode on other platforms. Checking for unicode just on SBCL isn't fair to others. :)

**Comment by pipping** [comment]
https://github.com/fare/asdf/blob/af27244845f708c61b709444956c07dad71efae5/uiop/common-lisp.lisp#L32-L39 might help. https://github.com/rpgoldman/asdf/pull/1 would also be relevant.
