### ISSUE TITLE
Add `t` as an alias for `*standard-window*` in all of the requisite functions

### ISSUE THREAD

**Issue by tarballs-are-good** [HiTECNOLOGYs/cl-charms#34]
Typing `*standard-window*` everywhere is maybe a bit verbose. Allowing `t`, like with `format`, might be a useful idiom.

**Comment by MatthewRock** [comment]
I'm merely a user, not a maintainer, but I'm against this idea.

`t` is known to be an alias to `*standard-output*`, and aliasing it again could be misleading.

Introduction of `t` as an alias would need to be introduced somehow, increasing learning curve.

Lastly, we could approach the problem by creating or altering macro(e.g. `with-curses`) that would allow one to define an alias to `*standard-window*`, or just let the user handle this, creating some variable himself.

**Comment by tarballs-are-good** [comment]
The meta-issue here is having to type `*standard-window*` all the time, and allowing us—developers/maintainers—to specify the idiomatic way to work with it. 

Options:
- `&optional` (I'm against)
- `&key` (Maybe for this...)
- Alias as `t` (I think this is kludgy but okay. I'm not concerned with confusion)
- Ask user to abbreviate with their own `defvar` (meh...)
- Modify `with-curses` (I can't think any good way to do this nicely)

**Comment by MatthewRock** [comment]
How about using `options` at last? `with-curses` has options, but it's currently unused. This way, we could do something like:

`(with-curses (win)
   (do-stuff-with win))`

Or, shorter version:

`(with-curses (w)
   (do-stuff-with w))`

Imho this is a good option.

**Comment by sjl** [comment]
I'm for the `t` alias myself.  I'll send a PR if you want it.

No one is going to be confused about `*standard-output*`.  The symbol `t` is a designator for at least two other things in Common Lisp according to the spec, not just `*standard-output*`.  It's a string designator `(string= t "T")` and a character designator `(character t) => #\T`.  The glossary also says it's a list designator (denoting a singleton list `(t)`) though I can't find anything that actually uses it like that.  Lisp has a history of punning `nil` and `t` to mean useful things, and I think this is a good way to reduce the end users' typing.

I'm not sure what the modification to `with-curses` would be, just binding `*standard-window*` to a variable?

```
(defmacro with-window (win &body body)
    `(let ((,win *standard-window*)) ,@body))
```

I think the standard window is used often enough that it's worth having a special case for, like `format`.  Hell, curses itself defines a complete second set of functions(/macros) just for dealing with it.

**Comment by tarballs-are-good** [comment]
I think we should go with `t`. I cannot think of a single reason against it. The way I would implement it is with a function called `resolve-window` or so, and define a compiler macro for it so that it returns `*standard-window*` for a constant argument `t`.

@sjl I would be happy if you could make a PR for this. If not, I can do it, when I can find time. I trust your opinion about this matter since you've written some substantial things with CL-CHARMS.

**Comment by sjl** [comment]
I'm not sure a compiler macro will do what you want.  E.g. for an example function:

```
(defun cursor-position (window)
  "Given a window WINDOW, return its X and Y coordinates as two values respectively."
  (let (x y)
    (charms/ll:getyx (window-pointer (resolve-window window)) y x)
    (values x y)))
```

The compiler macro would never get used, because it's only when the user actually calls this function that the `t` is going to appear.

If you really want to elide the `(eq t window)` check at runtime I think you'd need compiler macros for each high-level function.  You could use a macro to make that less painful:

```lisp
(defmacro defun-window (name arglist &body body)
  (let ((window (first arglist))
        (args (rest arglist))
        (function (alexandria:symbolicate name '%)))
    `(progn
       (defun ,function ,arglist
         ,@body)
       (defun ,name ,arglist
         (,function (resolve-window ,window) ,@args)) ;; wrong
       (define-compiler-macro ,name (&whole form window &rest args)
         (if (eq window t)
           (list* ',function '*standard-window* args)
           form))
       ',name)))
```

But that doesn't handle more complicated arglists properly, and would probably require a lot of fucking around with Alexandria's `parse-lambda-list` to get it right.

Personally I think a single `if` is not too much of a runtime cost to pay, but maybe there's a simpler way to save that cost that I haven't thought of.

**Comment by tarballs-are-good** [comment]
You're right, a compiler macro won't really give us much. Nix the idea. But the function *can* be inlined, at least.
