### ISSUE TITLE
[Question] charms/ll:getstr usage

### ISSUE THREAD

**Issue by dieggsy** [HiTECNOLOGYs/cl-charms#42]
**Note:** I'm completely new to ncurses and only have a couple weeks experience with SBCL. 

I was just following this example:

http://tldp.org/HOWTO/NCURSES-Programming-HOWTO/scanw.html

With the following code:

```lisp
(defun main (argv)
  (declare (ignore argv))
  (let ((mesg "Enter a string: ")
        (str (make-string 80))
        (row)
        (col))
    (charms/ll:initscr)
    (charms/ll:getmaxyx charms/ll:*stdscr* row col)
    (charms/ll:mvprintw (floor row 2) (floor (- col (length mesg)) 2) "%s" :string mesg)
    (charms/ll:getstr str)
    (charms/ll:mvprintw (- charms/ll:*LINES* 2) 0 "You entered: %s" :string str)
    (charms/ll:getch)
    (charms/ll:endwin)))
```

But nothing is printed after `"You entered"`, which I assume means `str` is still empty. Is this expected? What's the actual usage of getstr?

**Comment by tarballs-are-good** [comment]
@dieggsy Sorry for the late response. `getstr` requires a C-compatible string, which you can use CFFI to create. `make-string` is a string that only makes sense in Lisp space.

Check out these links:

- [`with-foreign-string`](https://common-lisp.net/project/cffi/manual/cffi-manual.html#with_002dforeign_002dstring)
- [`foreign-string-alloc`](https://common-lisp.net/project/cffi/manual/cffi-manual.html#foreign_002dstring_002dalloc)

**Comment by dieggsy** [comment]
I haven't gone back to this in ages, but I think you've given a complete answer, thanks.
